### ISSUE TITLE
Reference not Defined. /kafkaAdmin.js:21:2 

### ISSUE THREAD

**Issue by jlong23** [peterprib/node-red-contrib-kafka-manager#1]
0|node-red  | 3 Sep 13:10:14 - [debug] Kafka Broker {"label":"hostAvailable","host":"127.0.0.1","port":9092,"node":"db1bab3a.b34238"}
0|node-red  | 3 Sep 13:10:14 - [debug] Kafka Broker {"label":"hostAvailable connect","host":"127.0.0.1","port":9092,"node":"db1bab3a.b34238"}
0|node-red  | 3 Sep 13:09:19 - [info] [Kafka Admin:3a614d51.03d472] Initiating connection
0|node-red  | 3 Sep 13:09:19 - [info] [Kafka Admin:3a614d51.03d472] connected and processing 1 messages
0|node-red  | 3 Sep 13:09:19 - [debug] Kafka Admin {"label":"msgProcess","error":null,"data":[{},{"metadata":{},"clusterMetadata":{"controllerId":-1}}]}
0|node-red  | ReferenceError: err is not defined
0|node-red  |     at msgProcess (/home/kyootfox/.node-red/node_modules/node-red-contrib-kafka-manager/kafkaManager/kafkaAdmin.js:21:2)
0|node-red  |     at node.connection.listTopics (/home/kyootfox/.node-red/node_modules/node-red-contrib-kafka-manager/kafkaManager/kafkaAdmin.js:66:44)
0|node-red  |     at async.series (/home/kyootfox/.node-red/node_modules/kafka-node/lib/kafkaClient.js:919:7)
0|node-red  |     at /home/kyootfox/.node-red/node_modules/async/dist/async.js:3888:9
0|node-red  |     at /home/kyootfox/.node-red/node_modules/async/dist/async.js:473:16
0|node-red  |     at replenish (/home/kyootfox/.node-red/node_modules/async/dist/async.js:1006:25)
0|node-red  |     at iterateeCallback (/home/kyootfox/.node-red/node_modules/async/dist/async.js:995:17)
0|node-red  |     at /home/kyootfox/.node-red/node_modules/async/dist/async.js:969:16
0|node-red  |     at /home/kyootfox/.node-red/node_modules/async/dist/async.js:3885:13
0|node-red  |     at KafkaClient.wrappedFn (/home/kyootfox/.node-red/node_modules/kafka-node/lib/kafkaClient.js:481:14)
0|node-red  |     at KafkaClient.Client.invokeResponseCallback (/home/kyootfox/.node-red/node_modules/kafka-node/lib/baseClient.js:593:10)
0|node-red  |     at KafkaClient.Client.handleReceivedData (/home/kyootfox/.node-red/node_modules/kafka-node/lib/baseClient.js:569:10)
0|node-red  |     at KafkaClient.handleReceivedData (/home/kyootfox/.node-red/node_modules/kafka-node/lib/kafkaClient.js:1367:48)
0|node-red  |     at Socket.<anonymous> (/home/kyootfox/.node-red/node_modules/kafka-node/lib/kafkaClient.js:797:10)
0|node-red  |     at Socket.emit (events.js:198:13)
0|node-red  |     at addChunk (_stream_readable.js:288:12)
0|node-red  | 3 Sep 13:09:19 - [red] Uncaught Exception:
0|node-red  | 3 Sep 13:09:19 - ReferenceError: err is not defined
0

Flow:
[{"id":"56397e7e.c44c2","type":"inject","z":"a912827a.b674d","name":"","topic":"listTopics","payload":"{\"topic\":null}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":320,"y":160,"wires":[["3a614d51.03d472"]]}]

**Comment by peterprib** [comment]
Believe that issue was fixed in later version of code. Latest being 0.2.0  Had similar issue.  Have closed on assumption you are on earlier release.  Have fixed a few bugs in managing potential network issues in later releases.
