### ISSUE TITLE
logger sending message

### ISSUE THREAD

**Issue by lvenier** [peterprib/node-red-contrib-kafka-manager#12]
Hi Peter,

Thanks for logger.

I have updated to version 0.2.9
I have tried to use it to display/suppress debug message but was not able to achieve it.

I have a simple flow to produce and retrieve a message :
![image](https://user-images.githubusercontent.com/17571692/72469162-da06c200-37ac-11ea-9cb3-8b12f4134b4b.png)

Nothing spectacular. Whatever logger config I apply (Logger enabled or disabld) I still get messages on the console : 

_

> 15 Jan 15:36:59 - [debug] Kafka Broker {"label":"testHosts","node":"6ad70121.d54a1","available":true}
> 15 Jan 15:36:59 - [debug] Kafka Broker {"label":"testHost","host":"127.0.0.1","port":9092,"node":"6ad70121.d54a1"}
> 15 Jan 15:36:59 - [debug] Kafka Broker {"label":"hostAvailable","host":"127.0.0.1","port":9092,"node":"6ad70121.d54a1"}
> 15 Jan 15:36:59 - [debug] Kafka Broker {"label":"hostAvailable connect","host":"127.0.0.1","port":9092,"node":"6ad70121.d54a1"}
> 15 Jan 15:37:59 - [debug] Kafka Broker {"label":"testHosts","node":"6ad70121.d54a1","available":true}
> 15 Jan 15:37:59 - [debug] Kafka Broker {"label":"testHost","host":"127.0.0.1","port":9092,"node":"6ad70121.d54a1"}
> 15 Jan 15:37:59 - [debug] Kafka Broker {"label":"hostAvailable","host":"127.0.0.1","port":9092,"node":"6ad70121.d54a1"}
> 15 Jan 15:37:59 - [debug] Kafka Broker {"label":"hostAvailable connect","host":"127.0.0.1","port":9092,"node":"6ad70121.d54a1"}
> 15 Jan 15:38:16 - [debug] Kafka Producer {"label":"producerSend","node":"15505156.2bf11f"}
> 15 Jan 15:38:16 - [debug] Kafka Consumer Group {"label":"consumer.on.message","node":"89692785.dad198","message":{"topic":"SHAQ","value":"{\n    \"type\": \"test\"\n}","offset":650,"partition":0,"highWaterOffset":651,"key":"","timestamp":"2020-01-15T20:38:16.008Z"}}
> 15 Jan 15:38:16 - [debug] Kafka Consumer Group {"label":"sendMsg","node":"89692785.dad198","message":{"topic":"SHAQ","value":"{\n    \"type\": \"test\"\n}","offset":650,"partition":0,"highWaterOffset":651,"key":"","timestamp":"2020-01-15T20:38:16.008Z"}}

_

Did I miss something ?

Rgds

**Comment by peterprib** [comment]
Yep, the logging is per node and not across nodes.   The node logging is only for messages passing thru it.  On my wish list is to discover other types of nodes that have implement the logger and have a feature where it can be turned on or off.  This is a bit more complex and problematic and need to ponder solution.  Plus I don't have an actual need.  I assume that is what you were expecting.  

As I can wrap other nodes inputs/outputs, I could extend the logger node to act as a wrapper and extend to all nodes and/or selected nodes.  Did this with my queue manager contribution.

**Comment by lvenier** [comment]
ok but producer/consumer doest no really have output.... can not stop the log then ?

**Comment by peterprib** [comment]
By default each node auto stop after 100 debug sends for that node.  Can change default to first 20 or any number , even turn off.    Not sure what you mean in your comments.  

Could look to see mode of node-red and set accordingly.  Personally think its better to debug at start then stop as most likely time to have a problem is at start or stop of process.  Repeated logic is less likely to fail after repeated a few times
