### ISSUE TITLE
Bug on first install

### ISSUE THREAD

**Issue by JosefM95** [peterprib/node-red-contrib-kafka-manager#13]
Hi,

after install the package I get this errors:

![image](https://user-images.githubusercontent.com/32287688/73159016-c4b36100-40e5-11ea-8662-7eeaf63e5191.png)

I installed the package manualy using 'sudo npm install node-red-contrib-kafka-manager'.

**Comment by peterprib** [comment]
NPM seems to have failed to load dependencies in package.

   "dependencies": {
    "kafka-node": "*",
    "logger": "git+https://github.com/peterprib/node-red-contrib-logger.git"
  },

Must admit first time I tried to include dependency in this way

**Comment by peterprib** [comment]
have done but don't think this will fix issue as require points to logger and not node-red-contribute-logger.  Tell me if works other have to fix require as well

**Comment by joelgb2194** [comment]
I just tried installing the latest version of node-red-contrib-kafka-manager (0.2.10) and the latest node-red docker image, and I am having these same errors

**Comment by peterprib** [comment]
Will take a look at over week-end .  Think I know what the issue may be.

**Comment by joelgb2194** [comment]
I found the issue, it has to do with the `require("logger")` lines. It should be `require("node-red-contrib-logger")`

**Comment by peterprib** [comment]
have applied fixed and published
