### ISSUE TITLE
offsetOutOfRange

### ISSUE THREAD

**Issue by SEdilson** [peterprib/node-red-contrib-kafka-manager#15]
Hi Peter,
I'm new to kafka and your node, so i ran into this error:
```
2 Mar 09:55:01 - [error] [Kafka Consumer:1f872955.fae37f] on offsetOutOfRange Error: OffsetOutOfRange
```
When I use the local consumer i'm not getting this error.

Have you ever had to deal with this?
What could i do to solve it?

**Comment by peterprib** [comment]
Kafka issue.  From memory have to issue command to refresh cache

**Comment by SEdilson** [comment]
Hi Peter, first of all thanks for the help i stop the server and erased the files of the topic on ```/tmp/kafka-logs```
, after that i started again and the problem was gone. This issue can be closed, again thanks for helping me.
