### ISSUE TITLE
Kerberos support

### ISSUE THREAD

**Issue by akerckhofs-mycsn** [peterprib/node-red-contrib-kafka-manager#16]
Hi Peter,

Have you considered adding support for Kerberos? I've been looking for a node-red kafka implementation that supports it for quite a while but haven't been able to find one.

To implement it, you would need to set the `security.protocol` to SASL_PLAINTEXT, `sasl_mechanism` to GSSAPI and set the sasl.kerberos.principal, `sasl.kerberos.service.name` and point towards the location of the kerberos keytab in `sasl.kerberos.keytab` as shown in [the official librdkafka docs](https://github.com/edenhill/librdkafka/wiki/Using-SASL-with-librdkafka#5-configure-kafka-client-on-client-host).

Thanks in advance.

**Comment by peterprib** [comment]
The code is based on https://github.com/SOHU-Co/kafka-node so will support anything it supports.
