### ISSUE TITLE
Error when reconnecting

### ISSUE THREAD

**Issue by LordSuricato** [peterprib/node-red-contrib-kafka-manager#17]
What's in the flow?

A publisher node and a consumer node

What's going on?

If the broker/cluster restarts or if there is a network failure it does not reconnect

What should happen?

It should re-connect

How can I replicate it?

Deploy locally a producer and a consumer, remove the network and put it back. Another option is to reboot the server

**Comment by peterprib** [comment]
Thought tested these scenarios and it worked. Post relevant parts of log. Should log reconnect attempts. The reconnect logic is not part of my code. May be issue with node.kafka Send settings on connection.  So post these,  May be recent changes have upset matters.

**Comment by LordSuricato** [comment]
``` sh
20 Mar 09:47:22 - [warn] [Kafka Producer:14285a1c.3d0ee6] Connection down, queue depth reached 100
20 Mar 09:47:25 - [debug] Kafka Broker {"label":"testHosts","node":"311dcc9b.263b14","available":true}
20 Mar 09:47:25 - [debug] Kafka Broker {"label":"testHost","host":"127.0.0.1","port":9092,"node":"311dcc9b.263b14"}
20 Mar 09:47:25 - [debug] Kafka Broker {"label":"hostAvailable","host":"127.0.0.1","port":9092,"node":"311dcc9b.263b14"}
20 Mar 09:47:25 - [debug] Kafka Broker {"label":"hostAvailable connect","host":"127.0.0.1","port":9092,"node":"311dcc9b.263b14"}
20 Mar 09:47:35 - [debug] Kafka Broker {"label":"testHosts","node":"311dcc9b.263b14","available":true}
20 Mar 09:47:35 - [debug] Kafka Broker {"label":"testHost","host":"127.0.0.1","port":9092,"node":"311dcc9b.263b14"}
20 Mar 09:47:35 - [debug] Kafka Broker {"label":"hostAvailable","host":"127.0.0.1","port":9092,"node":"311dcc9b.263b14"}
20 Mar 09:47:35 - [debug] Kafka Broker {"label":"hostAvailable connect","host":"127.0.0.1","port":9092,"node":"311dcc9b.263b14"}
```

**Comment by peterprib** [comment]
That shows it has reconnected.  If you have sent more messages and seen nothing nothing queue it implies it has handed to node-kafka and it has accepted the messages.  Think the GUI should show green state.  

Do recall I had issues on consuming messages and why I have option to resume but can't remember circumstances that caused it.  If this is the issue, could improve by issuing resume on regularly basis if not manually put in this state.

**Comment by LordSuricato** [comment]
I noticed that the green status is not displayed. It shows "refreshBrokerMetadataFailed" for the consumer and for the producer who is adding messages to the queue. 
Yet the consumer does consume. The problem is that the producer doesn't produce and I think it's because the ready method is never triggered even if it's really connected (it doesn't change node.connected to true and therefore doesn't send).

**Comment by peterprib** [comment]
see https://github.com/SOHU-Co/kafka-node/issues/1378
