### ISSUE TITLE
Would like to set broker port via env var

### ISSUE THREAD

**Issue by hrbu** [peterprib/node-red-contrib-kafka-manager#19]
Hi Peter,

first of all, thanks for this component. One thing I would like to so improved:

## AS-IS
Currently the broker port is expected to be a number. This does NOT allow me to use an env-var instead of a hard-coded value.
![image](https://user-images.githubusercontent.com/10865951/77733253-dbebcd80-7006-11ea-86be-4011221f9d1a.png)

## TO-BE
I would prefer to NOT hard-code the port within my flow and rather (optionally) set it as an environment variable.

**Comment by peterprib** [comment]
Must admit was not  aware you could put in an environment variable into the field and it would be honored.  Will allow port to allow none numeric .   May be validate if numeric or env var.   Not sure what node-kafta may do if receives none numeric as may be passed in env var

**Comment by peterprib** [comment]
Just looked at code. Not easily done in way described as these aren't a 1 to 1 with base field so if the technique you describe does work on variables, it would not in this case as these are combined into the one variable with payload form [{host:"aaa",port:123},...].   May be able to offer ability for an environment variable to be used but would have to have form mentioned.   May be add a field for variable name and I merge the two  so one has best of both worlds

**Comment by peterprib** [comment]
have added feature to code

**Comment by hrbu** [comment]
Hi Peter, thanks for your fast response!!! The solution is almost perfect. As I can't remove the first connection entry within the ui, the final config contains both configs: `Kafka Broker {"hosts":[{"host":"kafka","port":29092},{"host":"","port":null}]}`. So it will not connect reliably. Could you please ignore connections entries with empty hosts ...

### UI:
![image](https://user-images.githubusercontent.com/10865951/77821857-af5eb100-70ed-11ea-97c7-07ce0d6727a3.png)

### Logs:
```
25 Mar 15:35:55 - [info] Starting modified flows
25 Mar 15:35:55 - [debug] Kafka Broker {"label":"test","hosts":[{"host":"kafka","port":29092}]}
25 Mar 15:35:55 - [debug] Kafka Broker {"hosts":[{"host":"kafka","port":29092},{"host":"","port":null}]}
25 Mar 15:35:55 - [info] Started modified flows
25 Mar 15:35:55 - [info] [Kafka Broker:Kafka Broker] state change up, processing 1 node scripts
25 Mar 15:35:55 - [info] [Kafka Consumer Group:mongo.vs3plus.changes_log] state change Up
25 Mar 15:35:55 - [debug] Kafka Consumer Group {"label":"brokerNode.stateUp","node":"75194869.2849b8"}
25 Mar 15:35:55 - [info] [Kafka Consumer Group:mongo.vs3plus.changes_log] state changed to up but not in ready state
25 Mar 15:35:55 - [debug] Kafka Producer {"label":"connect","node":"f2a1876.44a7378"}
25 Mar 15:35:55 - [debug] Kafka Consumer Group {"label":"connect","node":"75194869.2849b8"}
25 Mar 15:35:55 - [error] [Kafka Broker:Kafka Broker] hostAvailable on connect error Port should be >= 0 and < 65536. Received NaN.
25 Mar 15:35:55 - [info] [Kafka Producer:producer topic by message] connected and processing 0 messages
25 Mar 15:35:55 - [debug] Kafka Producer {"label":"producerSend","node":"f2a1876.44a7378"}
```

**Comment by peterprib** [comment]
published new version which allows first  entry to be deleted. This seemed the best way to fix problem point.

**Comment by hrbu** [comment]
Works perfectly. Thank you Peter. Greetings from Germany.

**Comment by peterprib** [comment]
"Ei Gude".  My Hessisch babbel,  Wife born in Bornheim.  My daughter born in Höchst.
