### ISSUE TITLE
Invalid topic if it contains "/"

### ISSUE THREAD

**Issue by janainascal** [peterprib/node-red-contrib-kafka-manager#28]
Hi there,

I'm having an error when the topic contains "/":
![Error log](https://user-images.githubusercontent.com/10633379/98377967-31b83780-2024-11eb-9e26-982fe7464646.png)

Since it is a common used used pattern in MQTT, and Kafka is commonly used to handle MQTT messages, I think it shouldn't be a issue.
In my case I need the "/" so I keep coherence with MQTT messages from others sources.

I hope this contribution is helpful
=)

**Comment by peterprib** [comment]
My code just passes thru to node-kafka and don't believe it does checking.  The error appears to be returned from kafka and from my reading it is a know limitation of kafka .   See https://www.ibm.com/support/knowledgecenter/SSMKHH_10.0.0/com.ibm.etools.mft.doc/bz91041_.html  Understand your issue as MQ uses this character in it topic handling routing.

**Comment by peterprib** [comment]
If it helps have written another set of nodes that emulate mq topic pub/sub model https://github.com/peterprib/node-red-contrib-pubsubhub.  I could add a feature to it to have subscription convert message to topic used for consumption.  Then for kafka could add option to translate topics from "/" to say "_-" and reverse however couldn't deal with lost part of topic in reverse translation.  The message could then be feed into Kafka.  Both these combined would then emulate MQ.

**Comment by janainascal** [comment]
Hey Peter,

Thanks for the ideia. I'll try it.

**Comment by peterprib** [comment]
If helps as I was adding wildcard consumer thought I would add feature option on producer to convert "/" to "." as it was easy to do and may help many people.
