### ISSUE TITLE
Kafka producer can't get the right properties of broker list from the Kafka Broker.

### ISSUE THREAD

**Issue by yiqiuheng** [peterprib/node-red-contrib-kafka-manager#3]
Hello Prib,

  Thanks for your contribution for the Kafka-manager package.
We have faced an error during the using of 'Kafka producer' of this package today :

If there are more than one broker is configured in the producer, kafka's producer connection would report an error. From the node-red log, we can see that the producer had some problems with the parsing string of the brokers that we have configured, and the parsed connection string was not standard.

If we only add on broker in the producer, it will be fine.

**Comment by yiqiuheng** [comment]
![2019-11-14_20h26_31](https://user-images.githubusercontent.com/7725129/68857231-5897a280-071d-11ea-90ef-6f6eded2bee0.png)

See the configured broker list in the image above,  
the parsed connection string will be : 174.34.85.85:9092 174.34.85.86:9092 174.34.85.87
But the right expected connection string should should be : 174.34.85.85:9092,174.34.85.86:9092,174.34.85.87:9092

**Comment by peterprib** [comment]
Admittedly I never test that part of logic.  added fix to change space to coma.  Not tested as take me a little time to get around to test so thought publish and you could try fix out.  Tell me if fix works.

**Comment by yiqiuheng** [comment]
Hello Peter, after testing today,  It does work now, thanks!
