### ISSUE TITLE
Wildcards on topic

### ISSUE THREAD

**Issue by janainascal** [peterprib/node-red-contrib-kafka-manager#30]
Hi @peterprib,

Please help with a question: Can I use wildcards on the topics?

I'm refatoring a service from AkkaStrams To NodeRed, and in Java I use a wildcard `*` for consumer subscription:
```java
Consumer.committableSource(consumerSettings, Subscriptions.topics("realms.*")){
         ...
}
```
But when I used on Consumer Group Node it not received the message:
![image](https://user-images.githubusercontent.com/10633379/98444870-0a7c6b80-20f3-11eb-8b9d-5ce34613b66f.png)

My debug nodes:
![image](https://user-images.githubusercontent.com/10633379/98444924-6646f480-20f3-11eb-908c-dbfaccfb4794.png)
![image](https://user-images.githubusercontent.com/10633379/98444892-326bcf00-20f3-11eb-960f-956cdb8c58a1.png)

If I set the exact topic it works fine:
![image](https://user-images.githubusercontent.com/10633379/98444983-d6557a80-20f3-11eb-807e-8e791b016173.png)

I don't know [kafka-node](https://github.com/SOHU-Co/kafka-node), so I don't know if wildcards works there.

**Comment by peterprib** [comment]
Hi, such a consideration would have to be delivered by Kafka server to work seamlessly.  My understanding, it doesn't.  It could be emulated by the consumer process continually polling the server and reacting to new topics added.  Could add such a feature if demand was strong enough.  It would require a new parameter for frequency of poll and would have to handle both topics added and deleted.  Must admit not sure if it would be a robust process.

**Comment by peterprib** [comment]
Hi, thought about it and decided it was a worthwhile thing as kafka not likely to provide in short term.  Latest version should allow willdcards using regex format.  Was a bit more effort than I originally thought.

**Comment by janainascal** [comment]
Hey Peter,
Thanks a lot!! I will test it.
