### ISSUE TITLE
Cannot access 'err' before initialization

### ISSUE THREAD

**Issue by lvenier** [peterprib/node-red-contrib-kafka-manager#4]
Hi Peter,

Thanks for your contrib.
I am testing your package and testing a very simple api call to check if a topic exist.

unfortunatly I got then an error and node-red crash with the following : 
_3 Dec 09:32:13 - [debug] Kafka Admin {"label":"msgProcess","error":{"errorCode":3}}
3 Dec 09:32:13 - [red] Uncaught Exception:
3 Dec 09:32:13 - ReferenceError: Cannot access 'err' before initialization
    at msgProcess (/home/lav/.node-red/node_modules/node-red-contrib-kafka-manager/kafkaManager/kafkaAdmin.js:22:11)
    at /home/lav/.node-red/node_modules/node-red-contrib-kafka-manager/kafkaManager/kafkaAdmin.js:83:58
    at /home/lav/.node-red/node_modules/kafka-node/lib/kafkaClient.js:1427:14
    at /home/lav/.node-red/node_modules/async/dist/async.js:3888:9
    at /home/lav/.node-red/node_modules/async/dist/async.js:473:16
    at iterateeCallback (/home/lav/.node-red/node_modules/async/dist/async.js:988:17)
    at /home/lav/.node-red/node_modules/async/dist/async.js:969:16
    at /home/lav/.node-red/node_modules/async/dist/async.js:3885:13
    at KafkaClient.wrappedFn (/home/lav/.node-red/node_modules/kafka-node/lib/kafkaClient.js:481:14)
    at KafkaClient.Client.invokeResponseCallback (/home/lav/.node-red/node_modules/kafka-node/lib/baseClient.js:591:10)__

Here the flow I am testing : 
_[{"id":"48e895d5.1aeeec","type":"tab","label":"Kafka","disabled":false,"info":""},{"id":"4700862d.135c58","type":"Kafka Admin","z":"48e895d5.1aeeec","name":"Kafka Admin","broker":"41a35b82.0507c4","x":490,"y":320,"wires":[["1e989567.8c8ccb","69ab509f.2f355"],["1826818c.e8512e"]]},{"id":"13a0b7a1.5dec28","type":"http in","z":"48e895d5.1aeeec","name":"[get] /topic","url":"/topic/:id","method":"get","upload":false,"swaggerDoc":"","x":200,"y":200,"wires":[["99e203ce.dcec5"]]},{"id":"f272d257.07441","type":"http in","z":"48e895d5.1aeeec","name":"[create] /topic","url":"/topic/:name","method":"post","upload":true,"swaggerDoc":"","x":210,"y":320,"wires":[["4700862d.135c58"]]},{"id":"99e203ce.dcec5","type":"function","z":"48e895d5.1aeeec","name":"describeConfigs","func":"msg.payload={type:'topic',name:msg.req.params.id};\nmsg.topic=\"describeConfigs\";\nreturn msg;","outputs":1,"noerr":0,"x":400,"y":200,"wires":[["4700862d.135c58"]]},{"id":"69ab509f.2f355","type":"http response","z":"48e895d5.1aeeec","name":"","statusCode":"","headers":{},"x":690,"y":320,"wires":[]},{"id":"1826818c.e8512e","type":"function","z":"48e895d5.1aeeec","name":"error 2 payload","func":"return msg;","outputs":1,"noerr":0,"x":700,"y":440,"wires":[["3c5f076e.ac5b18"]]},{"id":"3c5f076e.ac5b18","type":"http response","z":"48e895d5.1aeeec","name":"","statusCode":"","headers":{},"x":890,"y":440,"wires":[]},{"id":"1e989567.8c8ccb","type":"debug","z":"48e895d5.1aeeec","name":"","active":false,"tosidebar":true,"console":true,"tostatus":true,"complete":"payload","targetType":"msg","x":740,"y":240,"wires":[]},{"id":"41a35b82.0507c4","type":"Kafka Broker","z":"","name":"Kafka","hosts":[{"host":"127.0.0.1","port":9092}],"connectTimeout":"10000","requestTimeout":"30000","autoConnect":"true","idleConnection":"5","reconnectOnIdle":"true","maxAsyncRequests":"10","checkInterval":"10","usetls":false}]_

A simple test is : http://localhost:1880/topic/this_topic_does_not_exist

Hope you can help.
Let me know if you need further info.

**Comment by peterprib** [comment]
Fixed issue with uncaught exception.  Now latest published should process error "errorCode":3
