### ISSUE TITLE
Kafka Admin CreateTopic crashes Node Red...

### ISSUE THREAD

**Issue by mitch-shiver** [peterprib/node-red-contrib-kafka-manager#40]
Hi Peter,

Pretty cool idea to wrap kafka admin functions in a node red node.  I seem to be having an issue using it though, maybe it is something in my configuration.  I have a Linux system that is running Node Red, specs below under **My configuration**.  When I create the Node Red workflow in the image below under **My flow** using the Kafka Admin node, I get the exception under **My exception**, and Node Red crashes.

 (visually worked out from the test image at https://github.com/peterprib/node-red-contrib-kafka-manager#tests; I could not get the generalTest.json file to work, see details below.  The json file for my attempt is attached)

**My configuration:**
- Node-RED version: v2.0.4
- Node.js  version: v14.17.4
- Linux 3.10.0-862.el7.x86_64 x64 LE 

**My flow:**
![image](https://user-images.githubusercontent.com/4572588/145476805-b9a1d57f-521f-4760-9702-be0c3815f28d.png)

**My exception:**
```
9 Dec 10:57:38 - [red] Uncaught Exception:
9 Dec 10:57:38 - TypeError: topics.every is not a function
    at KafkaClient.createTopics (/home/pmc/.node-red/node_modules/kafka-node/lib/kafkaClient.js:931:14)
    at Admin.<anonymous> (/home/pmc/.node-red/node_modules/kafka-node/lib/admin.js:57:42)
    at Object.onceWrapper (events.js:519:28)
    at Admin.emit (events.js:400:28)
    at KafkaClient.<anonymous> (/home/pmc/.node-red/node_modules/kafka-node/lib/admin.js:20:10)
    at KafkaClient.emit (events.js:400:28)
    at /home/pmc/.node-red/node_modules/kafka-node/lib/kafkaClient.js:170:14
    at /home/pmc/.node-red/node_modules/async/dist/async.js:3888:9
    at /home/pmc/.node-red/node_modules/async/dist/async.js:473:16
    at replenish (/home/pmc/.node-red/node_modules/async/dist/async.js:1006:25)
```

Another question - How do you create that nice admin page under https://github.com/peterprib/node-red-contrib-kafka-manager#simple-web-admin-panel, is that part of package and I just did not find it yet?

Thanks!
Mitch

**Comment by peterprib** [comment]
Can I assume you worked out your problem as will fix the problem.  The admin panel is based on standard node-red features.

**Comment by mitch-shiver** [comment]
Hi Peter,
Yes, it was mostly ignorance on my part, so I closed the issue...
Thanks!Mitch
    On Friday, December 10, 2021, 06:48:43 PM PST, Peter Prib ***@***.***> wrote:  
 
 


Can I assume you worked out your problem as will fix the problem. The admin panel is based on standard node-red features.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
