### ISSUE TITLE
TypeError: done is not a function in KafkaBroker 

### ISSUE THREAD

**Issue by chudesno** [peterprib/node-red-contrib-kafka-manager#41]
When redeploying a flow error `TypeError: done is not a function` appears in the Debug messages.
It looks like it originates from `KafkaBrokerNode.close` at `kafkaManager/kafkaBroker.js:384:35`

It appears that nodered runtime itself defines that method with a different interface here:

```js
/**
 * Called when the node is being stopped
 * @param  {boolean} removed Whether the node has been removed, or just being stopped
 * @return {Promise} resolves when the node has closed
 */
Node.prototype.close = function(removed) {...}
```

May the method be renamed?

**Comment by peterprib** [comment]
Looking at the code , done is not used at 384 but can see reference to close definition at 374
     this.close = function (removed, done) { 

The code you have included, doesn't have the "removed" parameter which makes me concern that the underlying code has been changed somehow incorrectly by some process.  Not sure how renaming solves anything.  Renaming "this" to "node" could fix the issue, but not sure why it should have an impact as about context. 

Trying to recall if "removed" was introduced in code base as placed there to allow action to be take if the node had been removed from flow.  It implies the code base has been regressed or ungraded and this feature no longer exists.  The later sounds wrong as value add.

Need more information to properly resolve the issue.  Need to see extract of log which details problem and release information at start.

**Comment by peterprib** [comment]
assume issue is related to version of node-red being old

**Comment by peterprib** [comment]
surprise that it doesn't work on last version as doco implies it does.  Thought I had used on recent release so will take a look when I get a chance.

**Comment by chudesno** [comment]
For the clarity, I have not seen any issues with the functionality itself. This is just an error message appearing in `debug messages` panel on deploy.
Many thanks for looking into this, @peterprib !

**Comment by peterprib** [comment]
based on where occurring should have no material impact.  Will still fix.  Be interesting to understand why this call no longer aligns with documentation.  Have seen the message in v2.2
