### ISSUE TITLE
Set message key when publishing 

### ISSUE THREAD

**Issue by chainhead** [peterprib/node-red-contrib-kafka-manager#50]
How do I set message key when publishing messages to a topic?

**Comment by peterprib** [comment]
attribute on publish definition.  If y want more dynamic that is set per message that is a feature request.  Should be relatively easy to achieve  but needs to be a reasonable demand or reason.

**Comment by chainhead** [comment]
An example, please?

**Comment by peterprib** [comment]
see [node-red-contrib-kafka-manager](https://github.com/peterprib/node-red-contrib-kafka-manager)/[documentation](https://github.com/peterprib/node-red-contrib-kafka-manager/tree/master/documentation)/producer.JPG

**Comment by chainhead** [comment]
My key is a UUID so, I need to set it on a per message basis. Do we set the key with something like `msg.payload.key=`? 

How does "relatively easy to achieve" look like? I would like to take a stab?

**Comment by chainhead** [comment]
Set `msg.key` for dynamic setting of message key as described here.

**Comment by peterprib** [comment]
The method I will do will be more generic and may apply to other attributes as have a request to make some attributes set at configuration layer which I can see as valuable from a portability aspect.
