### ISSUE TITLE
Missing Monitor Flow from test/generaltest.json file

### ISSUE THREAD

**Issue by naveenkapoorRH** [peterprib/node-red-contrib-kafka-manager#62]
Was trying to run the test GUI. Looks very interesting.  Imported the test/generaltest json file into node-red.

NR couldn't find the "type": "Monitor Flow" node.  Any help would be appreciated.

**Comment by peterprib** [comment]
have to include  prib-functions https://github.com/peterprib/node-red-contrib-prib-functions for this node to work.
