### ISSUE TITLE
0.2.5 not latest version

### ISSUE THREAD

**Issue by lvenier** [peterprib/node-red-contrib-kafka-manager#7]
Hi Peter,

thanks for the PR.
I have updated nore-red with node-red-contrib-kafka-manager 0.2.5 and it still has the old code. PR is not in.
I have checked the master branch and looks correct. I guess the npm update went wrong somehow.
Can you release new version with latest code pls ?

Cheers.

**Comment by lvenier** [comment]
Banch Mater code :
		_let err=typeof errObject !== "string" ? errObject.toString() : errObject.message.toString();
		if(err.startsWith("Broker not available") || err.startsWith("Request timed out")) {_

0.2.5 code on  my dev : 
                _let err=typeof err !=="string"?err:err.message;
                if(err.startWith("Broker not available") || err.startWith("Request timed out")) {_

**Comment by peterprib** [comment]
Will look at when this evening.  Just setting off to work.  Thought I had done the right thing. Did notice some odd indications in eclipse but all seemed correct otherwise.

**Comment by lvenier** [comment]
ok... have a good day at work.

++

**Comment by peterprib** [comment]
hopefully published correctly this time.  My oddities have disappeared.

**Comment by lvenier** [comment]
updated on my local machine and looks all good.

Thanks a lot
