### ISSUE TITLE
removeTopics feature

### ISSUE THREAD

**Issue by lvenier** [peterprib/node-red-contrib-kafka-manager#8]
Hi Peter,

Any plan to add the removeTopics feature ?
The method exists on kafka-node.

**Comment by peterprib** [comment]
No plans but if you like it added and the method exists.  Can't see the method advertised nor in code.  If you can point it out I see what can be done.  If there is anything else mention it and I will give it a go,

**Comment by lvenier** [comment]
I suppose you are using : 
https://www.npmjs.com/package/kafka-node

the you have the following method : 

_> **removeTopics**(topics, cb)
> topics: Array, array of topics to remove
> cb: Function, the callback
> Example:
> 
> **consumer.removeTopics**(['t1', 't2'], function (err, removed) {
> });_

**Comment by peterprib** [comment]
Tracing it it code, it looks like its only referring to its own metadata and doesn't reach down into kafka itself.  Probably why it isn't exposed on admin function like create topic.  Will look to see if I can't do it myself.

**Comment by lvenier** [comment]
Hi Peter,

let me know if you need support.

**Comment by peterprib** [comment]
Whilst looking at remove topic noticed a bug in error offset which I have fixed.  Added in logic to do deletetopics if https://github.com/SOHU-Co/kafka-node improves it's code base which is different to remove topic as this is only a non persistent means of stopping a consumer connection listening to a topic.  Are you still interested in remove topic being implemented?  I notice that there are a few more KAFKA api's not implemented.

**Comment by lvenier** [comment]
Hi Peter,

yes would be interested to have it but depends on the compexity.
if kafka-node doest not have the logic it might be a tough path....

**Comment by peterprib** [comment]
Looked a kafka node and seems relatively simple as can use create topic as framework. Seems like only two modules need to be updated.

Put in stubs for this API call and other new Kafka API calls.   When get some free time will look at updating unless you want to do.

**Comment by lvenier** [comment]
Thanks Peter
I can have a look but as this is deep into the plugin logic I will require time to implement it.
I would like first to finnish the "debug" PR and can have a look after.
